pref("extensions.lore.relonturl", "chrome://lore/content/ontologies/austlitoaiore.owl");
pref("extensions.lore.dccreator","Anonymous");
pref("extensions.lore.rdfrepos", "http://austlit.edu.au/openrdf-sesame/repositories/lore");
pref("extensions.lore.rdfrepostype", "sesame");
pref("extensions.lore.tmkey","");
pref("extensions.lore.annoserver", "http://auselit.metadata.net/danno/annotea");
pref("extensions.lore.annotationmode", false);
pref("extensions.lore.DBG_LORE_UI", false);
pref("extensions.lore.DBG_LORE_ANNOTATIONS", false);
pref("extensions.lore.DBG_LORE_COMPOUND_OBJECTS", false);
pref("extensions.lore.DBG_LORE_TEXT_MINING", false);
pref("extensions.lore.DBG_LORE_PROFILING", false);
pref("extensions.lore.disable_annotations", false);
pref("extensions.lore.disable_compoundobjects", false);
pref("extensions.lore.disable_textmining", true);
pref("extensions.lore.filelogging", false);
pref("extensions.lore.high_contrast", false);
pref("extensions.lore.annocache_timeout", 1); // effectively disable for the moment
pref("extensions.lore.annotationMetadataOntologyURL", "chrome://lore/content/ontologies/AustLit.xml");
pref("extensions.lore.createprivateannotations", false);
pref("extensions.lore.ontologies",'[{\"nsprefix\":\"austlit\",\"locurl\":\"chrome://lore/content/ontologies/AustLit.xml\",\"useanno\":\"true\",\"useco\":\"false\", \"status\":\"default\", \"nsuri\":\"http://austlit.edu.au/owl/austlit.owl#\"},{\"nsuri\":\"http://RDVocab.info/Elements/\",\"nsprefix\":\"rda\",\"locurl\":\"chrome://lore/content/ontologies/rda.rdf\",\"useanno\":\"false\",\"useco\":\"false\", \"status\":\"custom\"},{\"nsprefix\":\"lore\", \"locurl\":\"chrome://lore/content/ontologies/austlitoaiore.owl\",\"useanno\":\"false\",\"useco\":\"true\", \"status\":\"default\", \"nsuri\":\"http://austlit.edu.au/owl/austlitore.owl#\"}]');