pref("extensions.lore.relonturl", "chrome://lore/content/ontologies/austlitoaiore.owl");
pref("extensions.lore.dccreator","Anonymous");
pref("extensions.lore.rdfrepos", "http://austlit.edu.au/openrdf-sesame/repositories/lore");
pref("extensions.lore.rdfrepostype", "sesame");
pref("extensions.lore.tmkey","");
pref("extensions.lore.annoserver", "http://auselit.metadata.net/danno/annotea");
pref("extensions.lore.annotationmode", false);
pref("extensions.lore.DBG_LORE_UI", false);
pref("extensions.lore.DBG_LORE_ANNOTATIONS", false);
pref("extensions.lore.DBG_LORE_COMPOUND_OBJECTS", false);
pref("extensions.lore.DBG_LORE_TEXT_MINING", false);
pref("extensions.lore.DBG_LORE_PROFILING", false);
pref("extensions.lore.disable_annotations", false);
pref("extensions.lore.disable_compoundobjects", false);
pref("extensions.lore.disable_textmining", true);
pref("extensions.lore.filelogging", false);
pref("extensions.lore.high_contrast", false);
pref("extensions.lore.annocache_timeout", 1); // effectively disable for the moment
pref("extensions.lore.annotationMetadataOntologyURL", "chrome://lore/content/ontologies/AustLit.xml");
pref("extensions.lore.createprivateannotations", false);
